"""Semantic ASR: evidence-preserving Japanese speech recognition."""

from .adaptive import AdaptiveKConfig, AdaptiveKDecision, select_adaptive_k
from .api import (
    PROFILES,
    RuntimeProfile,
    TranscriptResult,
    TranscriptSegment,
    load_transcriber,
    transcribe,
    transcribe_segments,
)
from .candidate_pool import aggregate_surface_candidates, merge_candidate_pools
from .cascade import CascadeConfig, CascadeDecision, run_candidate_cascade
from .context_catalog import (
    ContextCatalog,
    ContextEntry,
    ContextMatch,
    ContextSelection,
    load_context_catalog,
)
from .contracts import (
    CandidateEvidence,
    GateDecision,
    MoraUnit,
    NormalizedTranscript,
    ObservedTranscript,
    RankedCandidate,
)
from .discrete_unit_evidence import (
    DISCRETE_SURPRISAL_PAPER_REVISION,
    CentroidDistanceTable,
    CentroidDTWFeatures,
    CollapsedUnitSequence,
    DiscreteTokenLanguageModel,
    DiscreteUnitAcousticRanker,
    DiscreteUnitCandidateScore,
    DiscreteUnitSequence,
    DiscreteUnitSpace,
    DTWAlignment,
    DTWConfig,
    StaticTextToDiscreteUnitEncoder,
    SurprisalProfile,
    SurprisalThreshold,
    TranscriptGuidedFeatures,
    align_collapsed_units,
    centroid_dtw_features,
    pronunciation_feature_vector,
    transcript_guided_features,
)
from .document_scorer import (
    DocumentPromptFormat,
    GlobalScoreNormalization,
    SequenceScorerGlobalAdapter,
)
from .fusion import FusionConfig, fuse_candidates
from .japanese import mora_sequence, split_mora, to_katakana
from .longform_deliberation import (
    DeliberatedLongformResult,
    DeliberatedLongformSegment,
    DeliberatedObservedTranscript,
    DeliberatingSemanticASRTranscriber,
    LongformDeliberationConfig,
    PathArcReceipt,
    SegmentDeliberationTrace,
    SpanProposalProvider,
    apply_longform_deliberation,
    with_global_deliberation,
)
from .mbr import MBRDecision, SemanticMBRConfig, semantic_minimum_bayes_risk
from .multilevel_lattice import (
    BoundedUtility,
    CallableGlobalSequenceScorer,
    DeliberationLattice,
    DeliberationPolicy,
    DeliberationSpan,
    DocumentContext,
    GlobalBatchSequenceScorer,
    GlobalDeliberationDecision,
    GlobalPathScore,
    LatticeArc,
    PathHypothesis,
    SourcePath,
    SpanResolution,
    TransitionUtility,
    UtilityCalibrationProfile,
    decode_global_lattice,
    frozen_profile_digest,
    path_digest,
)
from .phonetic_bridge import (
    FrozenPronunciationLexicon,
    PhoneticBridgeConfig,
    PhoneticTextProposal,
    PronunciationLexiconEntry,
    propose_text_from_pronunciation,
)
from .phonetic_evidence import (
    CandidatePronunciation,
    CTCPronunciationScore,
    PhoneticCandidateEvidence,
    PosteriorFrame,
    PosteriorSequence,
    ctc_pronunciation_score,
    rank_candidate_pronunciations,
)
from .score_semantics import EvidenceScore, ScoreKind
from .semantic_deliberation import (
    ProjectedCandidate,
    SemanticDeliberationBuild,
    SemanticDeliberationConfig,
    VerifiedSpanProposal,
    build_semantic_deliberation_lattice,
    path_is_recombined,
    path_source_candidate_ids,
)

__all__ = [
    "PROFILES",
    "RuntimeProfile",
    "TranscriptResult",
    "TranscriptSegment",
    "load_transcriber",
    "transcribe",
    "transcribe_segments",
    "DISCRETE_SURPRISAL_PAPER_REVISION",
    "AdaptiveKConfig",
    "AdaptiveKDecision",
    "BoundedUtility",
    "CTCPronunciationScore",
    "CallableGlobalSequenceScorer",
    "CandidateEvidence",
    "CandidatePronunciation",
    "CentroidDTWFeatures",
    "CentroidDistanceTable",
    "CollapsedUnitSequence",
    "ContextCatalog",
    "ContextEntry",
    "ContextMatch",
    "ContextSelection",
    "CascadeConfig",
    "CascadeDecision",
    "DTWAlignment",
    "DTWConfig",
    "DeliberatedLongformResult",
    "DeliberatedLongformSegment",
    "DeliberatedObservedTranscript",
    "DeliberatingSemanticASRTranscriber",
    "DeliberationLattice",
    "DeliberationPolicy",
    "DeliberationSpan",
    "DiscreteTokenLanguageModel",
    "DiscreteUnitAcousticRanker",
    "DiscreteUnitCandidateScore",
    "DiscreteUnitSequence",
    "DiscreteUnitSpace",
    "DocumentContext",
    "DocumentPromptFormat",
    "EvidenceScore",
    "FrozenPronunciationLexicon",
    "FusionConfig",
    "GateDecision",
    "GlobalBatchSequenceScorer",
    "GlobalDeliberationDecision",
    "GlobalPathScore",
    "GlobalScoreNormalization",
    "LatticeArc",
    "LongformDeliberationConfig",
    "MBRDecision",
    "MoraUnit",
    "NormalizedTranscript",
    "ObservedTranscript",
    "PathArcReceipt",
    "PathHypothesis",
    "PhoneticBridgeConfig",
    "PhoneticCandidateEvidence",
    "PhoneticTextProposal",
    "PosteriorFrame",
    "PosteriorSequence",
    "ProjectedCandidate",
    "PronunciationLexiconEntry",
    "RankedCandidate",
    "ScoreKind",
    "SegmentDeliberationTrace",
    "SemanticDeliberationBuild",
    "SemanticDeliberationConfig",
    "SemanticMBRConfig",
    "SequenceScorerGlobalAdapter",
    "SourcePath",
    "SpanProposalProvider",
    "SpanResolution",
    "StaticTextToDiscreteUnitEncoder",
    "SurprisalProfile",
    "SurprisalThreshold",
    "TranscriptGuidedFeatures",
    "TransitionUtility",
    "UtilityCalibrationProfile",
    "VerifiedSpanProposal",
    "aggregate_surface_candidates",
    "align_collapsed_units",
    "apply_longform_deliberation",
    "build_semantic_deliberation_lattice",
    "centroid_dtw_features",
    "ctc_pronunciation_score",
    "decode_global_lattice",
    "frozen_profile_digest",
    "fuse_candidates",
    "load_context_catalog",
    "merge_candidate_pools",
    "mora_sequence",
    "path_digest",
    "path_is_recombined",
    "path_source_candidate_ids",
    "pronunciation_feature_vector",
    "propose_text_from_pronunciation",
    "rank_candidate_pronunciations",
    "run_candidate_cascade",
    "select_adaptive_k",
    "semantic_minimum_bayes_risk",
    "split_mora",
    "to_katakana",
    "transcript_guided_features",
    "with_global_deliberation",
]

__version__ = "0.2.0"
